Update start

diff --git a/start b/start
--- a/start
+++ b/start
@@ -38,7 +38,7 @@ print_rainbow() {
     echo -e "$reset"
 }
 cek_status() {
-    pm2 status | grep -q sellvpn && echo "aktif" || echo "nonaktif"
+    pm2 status | grep -q sellvpn2 && echo "aktif" || echo "nonaktif"
 }
 
 setup_bot() {
@@ -51,28 +51,28 @@ setup_bot() {
         echo -e "${green}Node.js is already installed, skipping...${neutral}"
     fi
 
-   rm -rf /root/BotVPN
+   rm -rf /root/BotVPN2
 
-    if [ ! -f /root/BotVPN/app.js ]; then
-        git clone https://github.com/kyt-team/BotVPN.git /root/BotVPN
+    if [ ! -f /root/BotVPN2/app.js ]; then
+        git clone https://github.com/kyt-team/BotVPN2.git /root/BotVPN2
     fi
 
 npm install -g npm@latest
 npm install -g pm2
 
-    if ! npm list --prefix /root/BotVPN express telegraf axios moment sqlite3 >/dev/null 2>&1; then
-        npm install --prefix /root/BotVPN sqlite3 express crypto telegraf axios dotenv
+    if ! npm list --prefix /root/BotVPN2 express telegraf axios moment sqlite3 >/dev/null 2>&1; then
+        npm install --prefix /root/BotVPN2 sqlite3 express crypto telegraf axios dotenv
     fi
 
-    if [ -n "$(ls -A /root/BotVPN)" ]; then
-        chmod +x /root/BotVPN/*
+    if [ -n "$(ls -A /root/BotVPN2)" ]; then
+        chmod +x /root/BotVPN2/*
     fi
 }
 
 server_app() {
     clear
     echo -e "${orange}─────────────────────────────────────────${neutral}"
-    echo -e "   ${green}.:::. BOT SELLVPN TELEGRAM .:::.   ${neutral}"
+    echo -e "   ${green}.:::. BOT sellvpn2 TELEGRAM .:::.   ${neutral}"
     echo -e "${orange}─────────────────────────────────────────${neutral}"
     echo -e "       ${green}•${neutral} server create user"
     echo -e "       ${green}•${neutral} server delete user"
@@ -107,7 +107,7 @@ server_app() {
 merchantid="NONE"
 apikey="NONE"
 groupid="-1001381824793"
-    rm -f /root/BotVPN/.vars.json
+    rm -f /root/BotVPN2/.vars.json
     echo "{
   \"BOT_TOKEN\": \"$token\",
   \"USER_ID\": \"$adminid\",
@@ -117,17 +117,17 @@ groupid="-1001381824793"
   \"DATA_QRIS\": \"$dataqris\",
   \"MERCHANT_ID\": \"$merchantid\",
   \"API_KEY\": \"$apikey\"
-}" >/root/BotVPN/.vars.json
+}" >/root/BotVPN2/.vars.json
 
-cat >/etc/systemd/system/sellvpn.service <<EOF
+cat >/etc/systemd/system/sellvpn2.service <<EOF
 [Unit]
-Description=SellVPN Bot Service
+Description=sellvpn2 Bot Service
 After=network.target
 
 [Service]
 Type=simple
-WorkingDirectory=/root/BotVPN
-ExecStart=/usr/bin/node /root/BotVPN/app.js
+WorkingDirectory=/root/BotVPN2
+ExecStart=/usr/bin/node /root/BotVPN2/app.js
 Restart=always
 User=root
 Environment=NODE_ENV=production
@@ -136,10 +136,10 @@ Environment=NODE_ENV=production
 WantedBy=multi-user.target
 EOF
 
-cat >/usr/bin/backup_sellvpn <<'EOF'
+cat >/usr/bin/backup_sellvpn2 <<'EOF'
 #!/bin/bash
-VARS_FILE="/root/BotVPN/.vars.json"
-DB_FILE="/root/BotVPN/sellvpn.db"
+VARS_FILE="/root/BotVPN2/.vars.json"
+DB_FILE="/root/BotVPN2/sellvpn2.db"
 
 if [ ! -f "$VARS_FILE" ]; then
     echo "❌ File $VARS_FILE tidak ditemukan"
@@ -167,31 +167,31 @@ fi
 EOF
 
 # bikin cron job tiap 1 jam
-cat >/etc/cron.d/backup_sellvpn <<'EOF'
+cat >/etc/cron.d/backup_sellvpn2 <<'EOF'
 SHELL=/bin/sh
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-0 0 * * * root /usr/bin/backup_sellvpn
+0 0 * * * root /usr/bin/backup_sellvpn2
 EOF
 
-chmod +x /usr/bin/backup_sellvpn
+chmod +x /usr/bin/backup_sellvpn2
 
 systemctl daemon-reload >/dev/null 2>&1
-systemctl enable sellvpn.service >/dev/null 2>&1
-systemctl start sellvpn.service >/dev/null 2>&1
-systemctl restart sellvpn.service >/dev/null 2>&1
+systemctl enable sellvpn2.service >/dev/null 2>&1
+systemctl start sellvpn2.service >/dev/null 2>&1
+systemctl restart sellvpn2.service >/dev/null 2>&1
 service cron restart
 
     printf "\033[5A\033[0J"
-    echo -e "       Status Server is "$(cek_status sellvpn.service)""
+    echo -e "       Status Server is "$(cek_status sellvpn2.service)""
     echo -e "${orange}─────────────────────────────────────────${neutral}"
     echo -e "${green}Bot has been installed and running.${neutral}"
     echo -e "${green}Type ${bold_white}/start${neutral} or ${bold_white}menu${neutral} in the telegram bot${neutral}"
 }
 
-if [[ ${1} == "sellvpn" ]]; then
+if [[ ${1} == "sellvpn2" ]]; then
     setup_bot
     server_app
 else
-    echo -e "${red}Invalid command. Use: ${yellow}start sellvpn${neutral}"
+    echo -e "${red}Invalid command. Use: ${yellow}start sellvpn2${neutral}"
     exit 1
 fi 
